## K-Fold Cross validation

##### Author  : Nabanita Paul

In [56]:
# Imporing dataset

from sklearn.datasets import load_iris

iris_data = load_iris()

In [4]:
iris_features = iris_data.data
iris_target = iris_data.target

In [9]:
iris_features.shape, iris_target.shape

((150, 4), (150,))

In [10]:
# Importing Cross validation score

from sklearn.model_selection import cross_val_score

## Model building

#### 1. Logistic regression



In [ ]:
from sklearn.linear_model import LogisticRegression

lr_model = LogisticRegression()

lr_score = cross_val_score(lr_model,iris_features,iris_target,cv=3)  


In [26]:
lr_score

array([0.98, 0.96, 0.98])

In [29]:
import numpy as np
avg_lr_score = np.average(lr_score)
avg_lr_score

0.9733333333333333

#### 2. Random forest

In [45]:
from sklearn.ensemble import RandomForestClassifier

rf_model = RandomForestClassifier()

rf_score = cross_val_score(rf_model,iris_features,iris_target,cv=3)  

In [46]:
rf_score

array([0.98, 0.94, 0.98])

In [47]:
import numpy as np
avg_rf_score = np.average(rf_score)
avg_rf_score

0.9666666666666667

#### 3. Support Vector machine

In [36]:
from sklearn.svm import SVC

SVM_model = SVC()

SVM_score = cross_val_score(SVM_model,iris_features,iris_target,cv=3)  

In [37]:
SVM_score

array([0.96, 0.98, 0.94])

In [38]:
import numpy as np
avg_SVM_score = np.average(SVM_score)
avg_SVM_score

0.96

In [51]:
model_comp = {" Model ":["Logistic Regression","Random Forest","Support Vector Machine"],"  3-fold Cross validation score  ":[lr_score,rf_score,SVM_score],
             "  Average Score  ":[avg_lr_score,avg_rf_score,avg_SVM_score]}
import pandas as pd
model_comp= pd.DataFrame(model_comp)


In [52]:
model_comp

Model    3-fold Cross validation score      Average Score  
0     Logistic Regression                [0.98, 0.96, 0.98]           0.973333
1           Random Forest                [0.98, 0.94, 0.98]           0.966667
2  Support Vector Machine                [0.96, 0.98, 0.94]           0.960000

#### Best Score is for logistic regression i.e 97.33%